name: Clone README.md
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy the README.md
      run: |
        sed 's/[.]\/docs\///' README.md > docs/README.md
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Clone the main README.md into docs/ dir"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        permission: "write"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
